### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Doc1.txt'

### ISSUE THREAD

**Issue by Katiyman** [spyrant/boolean-retrieval-engine#1]
Getting error while running the Indexer.py

Traceback (most recent call last):
  File "index.py", line 144, in <module>
    index(document_directory, dictionary_file, postings_file)   # call the indexer
  File "index.py", line 27, in index
    docID_list = [int(docID_string) for docID_string in os.listdir(document_directory)]
  File "index.py", line 27, in <listcomp>
    docID_list = [int(docID_string) for docID_string in os.listdir(document_directory)]
ValueError: invalid literal for int() with base 10: 'Doc1.txt'

I have provided folder path which has doc1.txt and doc2.txt

Does it expect the files in some other format
I am new to pythons so excuse if its not a good ques

**Comment by ahmedashour2230** [comment]
i need dictionary file and query file
